name: Perform release
on:
   workflow_dispatch:
      inputs:
         overrideMavenDistributionType:
            description: Override MAVEN_DISTRIBUTION_TYPE
            required: false
         doSiteDeployment:
            description: Do site deployment?
            required: true
            default: 'false'
env:
   GITHUB_TOKEN: ${{github.token}}
   MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
   MAVEN_CLI_ARGS: --batch-mode --update-snapshots
   MAVEN_RELEASE_ARGS: -Dreleasing
   TAG_NAME_FORMAT: '@{project.version}' # Note: If changing this format, you also have to adjust the checkout ref of the 'deploy-site' job.
   NEXT_DEVELOPMENT_VERSION: ${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.nextIncrementalVersion}-SNAPSHOT
   OVERRIDE_MAVEN_DISTRIBUTION_TYPE: ${{github.event.inputs.overrideMavenDistributionType}}
   MAVEN_DISTRIBUTION_TYPE: ${{secrets.MAVEN_DISTRIBUTION_TYPE}}
   MAVEN_DISTRIBUTION_SNAPSHOTS_URL: ${{secrets.MAVEN_DISTRIBUTION_SNAPSHOTS_URL}}
   MAVEN_DISTRIBUTION_RELEASES_URL: ${{secrets.MAVEN_DISTRIBUTION_RELEASES_URL}}
   MAVEN_DISTRIBUTION_USERNAME: ${{secrets.MAVEN_DISTRIBUTION_USERNAME}}
   MAVEN_DISTRIBUTION_PASSWORD: ${{secrets.MAVEN_DISTRIBUTION_PASSWORD}}
   GIT_USER_NAME: GitHub Actions (${{github.actor}})
   GIT_USER_EMAIL: ${{github.actor}}.actions@users.noreply.github.com
   GIT_COMMIT_MESSAGE_PREFIX: '[skip ci] '
jobs:
   create-release:
      if: startsWith(github.ref, 'refs/heads/release/')
      runs-on: ubuntu-latest
      outputs:
         releaseVersion: ${{steps.save-release-version.outputs.releaseVersion}}
      steps:
      -  uses: actions/checkout@v2
         with:
            token: ${{secrets.GH_WORKFLOW_TOKEN}}
      -  uses: actions/setup-java@v1
         with:
            java-version: 11
            server-id: maven-distribution
            server-username: MAVEN_DISTRIBUTION_USERNAME
            server-password: MAVEN_DISTRIBUTION_PASSWORD
      -  uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
            restore-keys: ${{runner.os}}-maven-
      -  run: .github/workflows/scripts/configure-git-user.sh
      -  run: .github/workflows/scripts/create-release.sh
      -  name: Save release version
         id: save-release-version
         run: .github/workflows/scripts/save-project-version.sh
         env:
            OUTPUT_VARIABLE_NAME: releaseVersion
            PROJECT_DIRECTORY: target/checkout
   deploy-site:
      needs: create-release
      if: github.event.inputs.doSiteDeployment == 'true'
      runs-on: ubuntu-latest
      steps:
      -  uses: actions/checkout@v2
         with:
            ref: ${{needs.create-release.outputs.releaseVersion}}
      -  uses: actions/setup-java@v1
         with:
            java-version: 11
      -  uses: actions/cache@v2
         with:
            path: ~/.m2/repository
            key: ${{runner.os}}-maven-${{hashFiles('**/pom.xml')}}
            restore-keys: ${{runner.os}}-maven-
      -  run: .github/workflows/scripts/configure-git-user.sh
      -  run: .github/workflows/scripts/deploy-site.sh